export const queryKeys = {
  projects: () => ["projects"] as const,
  board: (projectId: string) => ["board", projectId] as const,
  workItem: (id: string) => ["work-item", id] as const,
  threads: () => ["threads"] as const,
  thread: (workItemId?: string) => ["threads", workItemId ?? "none"] as const,
  dashboard: () => ["dashboard"] as const,
  agents: () => ["agents"] as const,
  budget: () => ["budget"] as const,
  agentDefinitions: () => ["agent-definitions"] as const,
  run: (id: string) => ["run", id] as const,
  runEvents: (runId: string) => ["run", runId, "events"] as const,
  threadMessages: (workItemId?: string) => ["threads", workItemId ?? "none", "messages"] as const,
  attachments: (workItemId: string) => ["attachments", workItemId] as const,
};
