/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a project by id */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update a project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{id}/board": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get project board (epic → feature → task tree) */
        get: operations["getProjectBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/work-items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a work item in a project */
        post: operations["createWorkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/work-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List work items with filters */
        get: operations["listWorkItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/work-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a work item by id */
        get: operations["getWorkItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a work item */
        patch: operations["updateWorkItem"];
        trace?: never;
    };
    "/work-items/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition work item status */
        post: operations["transitionWorkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List live agents */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agent definitions (settings) */
        get: operations["listAgentDefinitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update agent definition (model / token-limit / system-prompt / enabled) */
        patch: operations["updateAgentDefinition"];
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams */
        get: operations["listTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agent runs */
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get an agent run by id (steps, logLines, tokenUsage, cost, status) */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chat threads */
        get: operations["listThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List messages in a thread */
        get: operations["listThreadMessages"];
        put?: never;
        /** Post a message to a thread */
        post: operations["postThreadMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** SSE stream for agent replies and typing indicators in a thread */
        get: operations["streamThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard metrics (active agents, spend, tokens, counts) */
        get: operations["getDashboardMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/token-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get daily token usage series for bar chart */
        get: operations["getDashboardTokenUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity feed */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workspace token budget */
        get: operations["getBudget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            total?: number;
            page_size?: number;
            page_number?: number;
        };
        Envelope: {
            success: boolean;
            data?: unknown;
            error?: string | null;
            meta?: components["schemas"]["Meta"];
        };
        Attachment: {
            id: string;
            name: string;
            size: number;
            kind: string;
        };
        Agent: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "lead" | "sub";
            model: string;
            /** @enum {string} */
            status: "running" | "idle" | "paused";
            currentItemId?: string | null;
            progress?: number | null;
            tokenUsage?: number | null;
            tokenLimit: number;
        };
        Project: {
            id: string;
            name: string;
            repoUrl: string;
            itemCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectCreate: {
            name: string;
            repoUrl: string;
        };
        ProjectUpdate: {
            name?: string;
            repoUrl?: string;
        };
        WorkItem: {
            id: string;
            /** @enum {string} */
            type: "epic" | "feature" | "task";
            title: string;
            /** @enum {string} */
            status: "backlog" | "todo" | "in_progress" | "in_review" | "done";
            /** @enum {string} */
            priority: "low" | "medium" | "high" | "urgent";
            assignedAgent?: components["schemas"]["Agent"];
            epicId?: string | null;
            featureId?: string | null;
            projectId: string;
            tokenUsageThisRun?: number | null;
            tokenUsageAllRuns?: number | null;
            tokenLimit?: number | null;
            spec?: string | null;
            attachments?: components["schemas"]["Attachment"][] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkItemCreate: {
            /** @enum {string} */
            type: "epic" | "feature" | "task";
            title: string;
            /** @enum {string} */
            status: "backlog" | "todo" | "in_progress" | "in_review" | "done";
            /** @enum {string} */
            priority: "low" | "medium" | "high" | "urgent";
            epicId?: string;
            featureId?: string;
            spec?: string;
        };
        WorkItemUpdate: {
            title?: string;
            /** @enum {string} */
            priority?: "low" | "medium" | "high" | "urgent";
            epicId?: string;
            featureId?: string;
            assignedAgentId?: string;
            tokenLimit?: number;
            spec?: string;
        };
        Team: {
            id: string;
            name: string;
        };
        AgentDefinition: {
            id: string;
            teamId: string;
            role: string;
            model: string;
            tokenLimit: number;
            systemPrompt?: string | null;
            enabled: boolean;
        };
        AgentDefinitionUpdate: {
            model?: string;
            tokenLimit?: number;
            systemPrompt?: string;
            enabled?: boolean;
        };
        Message: {
            id: string;
            conversationId: string;
            /** @enum {string} */
            role: "user" | "agent" | "lead_agent";
            agentId?: string | null;
            content: string;
            attachments?: components["schemas"]["Attachment"][] | null;
            /** Format: date-time */
            createdAt: string;
        };
        Thread: {
            id: string;
            agentId: string;
            workItemId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        StageStateOut: {
            stage: string;
            status: string;
            role?: string | null;
            startedAt?: string | null;
            endedAt?: string | null;
        };
        GateOut: {
            kind: string;
            stage: string;
        };
        RunOut: {
            id: string;
            workItemId: string;
            projectId: string;
            autonomyLevel: string;
            status: string;
            currentStage?: string | null;
            stages: components["schemas"]["StageStateOut"][];
            pendingGate?: components["schemas"]["GateOut"] | null;
            createdAt: string;
            updatedAt: string;
            startedAt?: string | null;
            endedAt?: string | null;
            tokenUsage: number;
            cost: number;
        };
        RunEventOut: {
            id: string;
            runId: string;
            seq: number;
            stage?: string | null;
            role?: string | null;
            type: string;
            payload: Record<string, unknown>;
            createdAt: string;
        };
        DashboardMetrics: {
            activeAgents: number;
            totalSpend: number;
            totalTokens: number;
            projectCount: number;
            workItemCount: number;
        };
        TokenUsagePoint: {
            /** Format: date */
            day: string;
            tokens: number;
        };
        ActivityEvent: {
            id: string;
            /** @enum {string} */
            type: "agent_write" | "status_change" | "run_complete" | "run_failed";
            description: string;
            agentId?: string | null;
            workItemId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        Budget: {
            used: number;
            limit: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                page_size?: number;
                page_number?: number;
                order_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Project"][];
                        meta?: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Project"];
                    };
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Project"];
                    };
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Project"];
                    };
                };
            };
        };
    };
    getProjectBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["WorkItem"][];
                    };
                };
            };
        };
    };
    createWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkItemCreate"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["WorkItem"];
                    };
                };
            };
        };
    };
    listWorkItems: {
        parameters: {
            query?: {
                status?: "backlog" | "todo" | "in_progress" | "in_review" | "done";
                epic?: string;
                project?: string;
                page_size?: number;
                page_number?: number;
                order_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["WorkItem"][];
                        meta?: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    getWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["WorkItem"];
                    };
                };
            };
        };
    };
    updateWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkItemUpdate"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["WorkItem"];
                    };
                };
            };
        };
    };
    transitionWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "backlog" | "todo" | "in_progress" | "in_review" | "done";
                };
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["WorkItem"];
                    };
                };
            };
            /** @description invalid transition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Agent"][];
                    };
                };
            };
        };
    };
    listAgentDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AgentDefinition"][];
                    };
                };
            };
        };
    };
    updateAgentDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentDefinitionUpdate"];
            };
        };
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["AgentDefinition"];
                    };
                };
            };
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Team"][];
                    };
                };
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                page_size?: number;
                page_number?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RunOut"][];
                        meta?: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["RunOut"];
                    };
                };
            };
        };
    };
    listThreads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Thread"][];
                    };
                };
            };
        };
    };
    listThreadMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Message"][];
                    };
                };
            };
        };
    };
    postThreadMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Message"];
                    };
                };
            };
        };
    };
    streamThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getDashboardMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["DashboardMetrics"];
                    };
                };
            };
        };
    };
    getDashboardTokenUsage: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["TokenUsagePoint"][];
                    };
                };
            };
        };
    };
    listActivity: {
        parameters: {
            query?: {
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["ActivityEvent"][];
                    };
                };
            };
        };
    };
    getBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"] & {
                        data?: components["schemas"]["Budget"];
                    };
                };
            };
        };
    };
}
