from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol

from naaf_db.ports import PaginatedResult, Repository  # noqa: F401


class UnitOfWork(Protocol):
    """The app-specific UnitOfWork protocol (named naaf repositories)."""

    def transaction(self) -> AbstractContextManager[Any]: ...

    @property
    def projects(self) -> Repository: ...
    @property
    def work_items(self) -> Repository: ...
    @property
    def teams(self) -> Repository: ...
    @property
    def agent_definitions(self) -> Repository: ...
    @property
    def runs(self) -> Repository: ...
    @property
    def run_events(self) -> Repository: ...
    @property
    def agent_events(self) -> Repository: ...
    @property
    def notifications(self) -> Repository: ...
    @property
    def messages(self) -> Repository: ...
